services:
  - type: web
    name: openstocks
    runtime: node
    plan: free
    buildCommand: yarn --frozen-lockfile install
    startCommand: node dist/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PATH
        value: ./data/openstocks.sqlite
